/**
 * Azure KeyVault REST API
 * REST API for interacting with Azure Key Vault
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BinaryData {
    'length'?: number;
    'replayable'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "length",
            "baseName": "length",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "replayable",
            "baseName": "replayable",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BinaryData.attributeTypeMap;
    }

    public constructor() {
    }
}
