/**
 * Azure KeyVault REST API
 * REST API for interacting with Azure Key Vault
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class JsonWebKey {
    'keyType'?: string;
    'keyOps'?: Array<string>;
    'n'?: string;
    'e'?: string;
    'd'?: string;
    'dp'?: string;
    'dq'?: string;
    'qi'?: string;
    'p'?: string;
    'q'?: string;
    'k'?: string;
    't'?: string;
    'x'?: string;
    'y'?: string;
    'id'?: string;
    'valid'?: boolean;
    'curveName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "keyType",
            "baseName": "keyType",
            "type": "string",
            "format": ""
        },
        {
            "name": "keyOps",
            "baseName": "keyOps",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "n",
            "baseName": "n",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "e",
            "baseName": "e",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "d",
            "baseName": "d",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "dp",
            "baseName": "dp",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "dq",
            "baseName": "dq",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "qi",
            "baseName": "qi",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "p",
            "baseName": "p",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "q",
            "baseName": "q",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "k",
            "baseName": "k",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "t",
            "baseName": "t",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "x",
            "baseName": "x",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "y",
            "baseName": "y",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "valid",
            "baseName": "valid",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "curveName",
            "baseName": "curveName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JsonWebKey.attributeTypeMap;
    }

    public constructor() {
    }
}
