/**
 * Azure KeyVault REST API
 * REST API for interacting with Azure Key Vault
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { KeyReleasePolicy } from '../models/KeyReleasePolicy';
import { HttpFile } from '../http/http';

export class KeyProperties {
    'enabled'?: boolean;
    'exportable'?: boolean;
    'notBefore'?: Date;
    'version'?: string;
    'expiresOn'?: Date;
    'createdOn'?: Date;
    'updatedOn'?: Date;
    'recoveryLevel'?: string;
    'name'?: string;
    'id'?: string;
    'tags'?: { [key: string]: string; };
    'managed'?: boolean;
    'recoverableDays'?: number;
    'releasePolicy'?: KeyReleasePolicy;
    'hsmPlatform'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "exportable",
            "baseName": "exportable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "notBefore",
            "baseName": "notBefore",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiresOn",
            "baseName": "expiresOn",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdOn",
            "baseName": "createdOn",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedOn",
            "baseName": "updatedOn",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "recoveryLevel",
            "baseName": "recoveryLevel",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "managed",
            "baseName": "managed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "recoverableDays",
            "baseName": "recoverableDays",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "releasePolicy",
            "baseName": "releasePolicy",
            "type": "KeyReleasePolicy",
            "format": ""
        },
        {
            "name": "hsmPlatform",
            "baseName": "hsmPlatform",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KeyProperties.attributeTypeMap;
    }

    public constructor() {
    }
}
