/**
 * Azure KeyVault REST API
 * REST API for interacting with Azure Key Vault
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JsonWebKey } from '../models/JsonWebKey';
import { KeyProperties } from '../models/KeyProperties';
import { HttpFile } from '../http/http';

export class KeyVaultKey {
    'key'?: JsonWebKey;
    'properties'?: KeyProperties;
    'name'?: string;
    'id'?: string;
    'keyType'?: string;
    'keyOperations'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "JsonWebKey",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "KeyProperties",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "keyType",
            "baseName": "keyType",
            "type": "string",
            "format": ""
        },
        {
            "name": "keyOperations",
            "baseName": "keyOperations",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return KeyVaultKey.attributeTypeMap;
    }

    public constructor() {
    }
}
